name: dbt CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "duckdb==1.5.4" dbt-duckdb

      - name: Load testing data
        run: |
          cd streaming_warehouse
          dbt seed --profiles-dir . --target ci

      - name: Run dbt models
        env:
          motherduck_token: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: |
          cd streaming_warehouse
          dbt run --profiles-dir . --target ci

      - name: Run dbt tests
        env:
          motherduck_token: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: |
          cd streaming_warehouse
          dbt test --profiles-dir . --target ci
